### ISSUE TITLE
Shaky caret on Firefox

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#1056]
## Description

On Firefox, the expression shakes a little bit when moving the caret around.

For what it's worth, one fix is injecting the following styles into mathlive 

```css
math-field:hover,
  math-field:focus,
  math-field:focus-within {
    outline: var(--border-color-secondary) auto 1px;
  }
  math-field {
    transition: outline 0.2s ease-in-out;
  }
```

## Steps to Reproduce

1. Be on Firefox with Windows 10
2. Go to https://cortexjs.io/mathlive/
3. Paste in `\begin{equation*} \frac{3}{3+5} \end{equation*}`
4. Put the caret at the end of the mathfield
5. Hit the `left` arrow key

### Actual Behavior

![2021-06-27-0166](https://user-images.githubusercontent.com/10220080/123540055-48d7a100-d73d-11eb-868f-45ced687e3d5.gif)

### Expected Behavior

No shaking

### Environment

**MathLive version** v0.69.4

**Operating System** Windows 10

**Browser** Firefox

**Comment by stefnotch** [comment]
A fix for the caret is to use box-shadows
```css
.ML__caret:after {
          border-right-width: 0px !important;
          margin-right: 0px !important;
          width: 0px !important;
          box-shadow: 0px 0px 0px 1px var(--caret,hsl(var(--hue,212),40%,49%));
         }
```
