### ISSUE TITLE
Display of some icons are 

### ISSUE THREAD

**Issue by macychan1** [arnog/mathlive#2026]
![image](https://github.com/arnog/mathlive/assets/59677452/eddb403f-bb62-4bd9-94a9-5b351404bfdd)
Hi, 
.ML__keyboard .ML__keyboard--plate div .rows>ul>li svg.svg-glyph {
    padding: 8px 0;
    width: 20px;
    height: 20px;
}
This style causes the grey button icon very small, is there any way to fix?

**Comment by arnog** [comment]
I would recommend you update to the current version of MathLive. I don't think this rule would do anything in the current version.

Your rule is also *way* more specific than needed. Something like this would be more than enough:

```css
.ML__keyboard .MLK__rows > .row div svg.svg-glyph {
    height: 12px;
    min-height: 12px;
}
```

I'm also unsure of what you're trying to do, but if you're trying to set the glyph to be a specific size, you only need to set the `height` and `min-height` (if you want a height less than the 20px default).
