### ISSUE TITLE
Disable the keyboard icon in all devices not working 

### ISSUE THREAD

**Issue by AbhishekNayak007** [arnog/mathlive#2098]
## Description
I disabled the mathlive virtual keyboard icon in the desktop mode by using this css code but it is still showing the keyboard icon in tablet ??
```
@media not (pointer: coarse) {
  math-field::part(virtual-keyboard-toggle) {
    display: none !important;
  }
}
```

**Comment by arnog** [comment]
Right. The code seems to be doing what it says: when the device has a mouse, hide the virtual keyboard toggle, otherwise, keep it visible. If you want to always hide the keyboard toggle, you should remove the media query, i.e. 

```css
  math-field::part(virtual-keyboard-toggle) {
    display: none !important;
  }
```
