### ISSUE TITLE
Selection color of fractions

### ISSUE THREAD

**Issue by JR-1991** [arnog/mathlive#2589]
Can the selection color be changed or the font color inverted when clicking a fraction? I'm looking to implement a dark mode, but the current selection clashes with the bright font color.

<img width="195" alt="Image" src="https://github.com/user-attachments/assets/70cb113d-6f23-41b7-8d39-276008cd2bda" />

I have tried the CSS options documented but with no success. I appreciate any help you can provide.

**Comment by JR-1991** [comment]
Thank you for your reply, but this unfortunately did not resolve the issue. It appears unrelated to the selection specified by 
`--selection-color`. I've included a GIF to demonstrate the problem, and I've set the selection to red for emphasis.

![Image](https://github.com/user-attachments/assets/9e089f78-b79b-4fa7-a39b-c97406710146)

This is the corresponding CSS I have used:

```css
math-field {
    background: transparent;
    background-color: transparent;
    --selection-background-color: red;
    --selection-color: red;
}
```

Do you know how I can change this? I am using it within a React app.
